# Generated by Django 6.0.3 on 2026-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard"),
                            ("GST", "GST"),
                            ("Duplicate", "Duplicate"),
                        ],
                        default="Standard",
                        max_length=20,
                    ),
                ),
                ("start_no", models.IntegerField()),
                ("end_no", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
