# Generated by Django 6.0.3 on 2026-03-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billrecord",
            name="added_by",
            field=models.CharField(default="Chandrakumar", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billrecord",
            name="bill_type",
            field=models.CharField(default="Standard", max_length=50),
        ),
    ]
