# Generated by Django 6.0.3 on 2026-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_billrecord_added_by_alter_billrecord_bill_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billrecord",
            name="added_by",
            field=models.CharField(default="Admin", max_length=50),
        ),
    ]
