# Generated by Django 6.0.3 on 2026-03-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_billrecord_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billrecord",
            name="bill_type",
            field=models.CharField(default="bill book", max_length=50),
        ),
    ]
