# Generated by Django 6.0.3 on 2026-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_alter_billrecord_bill_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="billrecord",
            name="books",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="billrecord",
            name="pages",
            field=models.IntegerField(default=0),
        ),
    ]
